spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/person
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 961021
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
         max-active: 50
         max-wait: 3000
         max-idle: 20
         min-idle: 2
    timeout: 5000
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true


server:
  port: 8181

